-- 来杯好卦爻一爻 · 离线常用整词拼音词库
-- 无声调、无空格拼音 -> 常用词。优先覆盖日常问句及十四类占问场景。
return {
  nihao = { "你好" }, ninhao = { "您好" }, zaijian = { "再见" }, xiexie = { "谢谢" },
  buxiekeqi = { "不谢客气" }, qingwen = { "请问" }, mafan = { "麻烦" }, bangzhu = { "帮助" },
  wo = { "我" }, women = { "我们" }, nimen = { "你们" }, tamen = { "他们", "她们" },
  ziji = { "自己" }, duifang = { "对方" }, bieren = { "别人" }, dajia = { "大家" },
  jintian = { "今天" }, mingtian = { "明天" }, houtian = { "后天" }, zuotian = { "昨天" },
  qiantian = { "前天" }, xianzai = { "现在" }, yihou = { "以后" }, yiqian = { "以前" },
  zuijin = { "最近" }, weilai = { "未来" }, nianfen = { "年份" }, shijian = { "时间" },
  shenme = { "什么" }, weishenme = { "为什么" }, zenme = { "怎么" }, zenmeyang = { "怎么样" },
  shifou = { "是否" }, keyi = { "可以" }, nengbu = { "能不" }, nengfou = { "能否" },
  shenmeshihou = { "什么时候" }, duojiu = { "多久" }, nali = { "哪里" }, nar = { "哪儿" },
  zenyang = { "怎样" }, ruhe = { "如何" }, jieguo = { "结果" }, daan = { "答案" },
  haobuhao = { "好不好" }, xingbuxing = { "行不行" }, duibudui = { "对不对" }, youmeiyou = { "有没有" },
  xiwang = { "希望" }, danxin = { "担心" }, haipa = { "害怕" }, jiaolv = { "焦虑" },
  kaolv = { "考虑" }, juede = { "觉得" }, renwei = { "认为" }, xiangyao = { "想要" },
  xuyao = { "需要" }, yinggai = { "应该" }, bixu = { "必须" }, keneng = { "可能" },
  yiding = { "一定" }, yexu = { "也许" }, yijing = { "已经" }, rengran = { "仍然" },
  zhunbei = { "准备" }, jueding = { "决定" }, xuanze = { "选择" }, jihua = { "计划" },
  kaishi = { "开始" }, jieshu = { "结束" }, jixu = { "继续" }, fangqi = { "放弃" },
  chenggong = { "成功" }, shibai = { "失败" }, shunli = { "顺利" }, kunnan = { "困难" },
  wenti = { "问题" }, banfa = { "办法" }, fangfa = { "方法" }, jianyi = { "建议" },
  jihui = { "机会" }, fengxian = { "风险" }, bianhua = { "变化" }, fazhan = { "发展" },
  faxian = { "发现" }, fangxiang = { "方向" }, mubiao = { "目标" }, yuanyin = { "原因" },
  qingkuang = { "情况" }, zhuangtai = { "状态" }, guanxi = { "关系" }, yingxiang = { "影响" },
  chuli = { "处理" }, jiejue = { "解决" }, gaishan = { "改善" }, tiaozheng = { "调整" },
  dengdai = { "等待" }, lianxi = { "联系" }, goutong = { "沟通" }, jianmian = { "见面" },

  xueye = { "学业" }, xuexi = { "学习" }, xuexiao = { "学校" }, xuesheng = { "学生" },
  laoshi = { "老师" }, tongxue = { "同学" }, kecheng = { "课程" }, zuoye = { "作业" },
  kaoshi = { "考试" }, chengji = { "成绩" }, fenshu = { "分数" }, paiming = { "排名" },
  shengxue = { "升学" }, gaokao = { "高考" }, zhongkao = { "中考" }, kaoyan = { "考研" },
  liuxue = { "留学" }, baoming = { "报名" }, luqu = { "录取" }, biye = { "毕业" },
  lunwen = { "论文" }, zhuanye = { "专业" }, zhuanxue = { "转学" }, fuxi = { "复习" },
  yuxi = { "预习" }, tingke = { "听课" }, zixue = { "自学" }, jiangxuejin = { "奖学金" },

  shiye = { "事业" }, gongzuo = { "工作" }, zhiye = { "职业" }, gongsi = { "公司" },
  danwei = { "单位" }, lingdao = { "领导" }, tongshi = { "同事" }, kehu = { "客户" },
  xiangmu = { "项目" }, renwu = { "任务" }, hetong = { "合同" }, huiyi = { "会议" },
  mianshi = { "面试" }, qiuzhi = { "求职" }, zhaopin = { "招聘" }, ruzhi = { "入职" },
  lizhi = { "离职" }, tiaocao = { "跳槽" }, shengzhi = { "升职" }, jiangzhi = { "降职" },
  jiaxin = { "加薪" }, gongzi = { "工资" }, jiangjin = { "奖金" }, yeji = { "业绩" },
  chuangye = { "创业" }, kaiye = { "开业" }, hezuo = { "合作" }, jingzheng = { "竞争" },
  tanpan = { "谈判" }, chuchai = { "出差" }, zhuangang = { "转岗" }, gaihang = { "改行" },
  shengyi = { "生意" }, shangye = { "商业" }, dianpu = { "店铺" }, dingdan = { "订单" },

  aiqing = { "爱情" }, ganqing = { "感情" }, lianai = { "恋爱" }, hunyin = { "婚姻" },
  duixiang = { "对象" }, nanpengyou = { "男朋友" }, nvpengyou = { "女朋友" }, peiou = { "配偶" },
  xihuan = { "喜欢" }, aishang = { "爱上" }, zhuiqiu = { "追求" }, biaobai = { "表白" },
  yuehui = { "约会" }, xiangqin = { "相亲" }, jiehun = { "结婚" }, dinghun = { "订婚" },
  fuhe = { "复合" }, fenshou = { "分手" }, lihun = { "离婚" }, lengzhan = { "冷战" },
  zhengchao = { "争吵" }, maodun = { "矛盾" }, yuanfen = { "缘分" }, taohua = { "桃花" },
  zhenxin = { "真心" }, xinren = { "信任" }, zhongcheng = { "忠诚" }, beipan = { "背叛" },
  disanfang = { "第三方" }, qianren = { "前任" }, jiating = { "家庭" }, jiazhang = { "家长" },

  caiyun = { "财运" }, caifu = { "财富" }, qiancai = { "钱财" }, shouru = { "收入" },
  zhichu = { "支出" }, cunkuan = { "存款" }, qian = { "钱" }, zijin = { "资金" },
  touzi = { "投资" }, licai = { "理财" }, gupiao = { "股票" }, jijin = { "基金" },
  fangchan = { "房产" }, maifang = { "买房" }, maimai = { "买卖" }, jiaoyi = { "交易" },
  yingli = { "盈利" }, kuisun = { "亏损" }, huikuan = { "回款" }, zhouzhuan = { "周转" },
  zhaiwu = { "债务" }, jieqian = { "借钱" }, huanqian = { "还钱" }, daikuan = { "贷款" },
  zhangjia = { "涨价" }, jiangjia = { "降价" }, zengzhi = { "增值" }, baozhi = { "保值" },

  diushi = { "丢失" }, shiwu = { "失物" }, zhaodao = { "找到" }, xunzhao = { "寻找" },
  xunren = { "寻人" }, zhaoren = { "找人" }, shizong = { "失踪" }, luoshi = { "落实" },
  shouji = { "手机" }, qianbao = { "钱包" }, yaoshi = { "钥匙" }, zhengjian = { "证件" },
  shenfenzheng = { "身份证" }, yinhangka = { "银行卡" }, xingli = { "行李" }, shoubiao = { "手表" },
  xianglian = { "项链" }, jiezhi = { "戒指" }, chongwu = { "宠物" }, maomi = { "猫咪" },
  gougou = { "狗狗" }, beitou = { "被偷" }, wangji = { "忘记" }, didian = { "地点" },

  susong = { "诉讼" }, guansi = { "官司" }, falv = { "法律" }, lvshi = { "律师" },
  fayuan = { "法院" }, kaiting = { "开庭" }, panjue = { "判决" }, shangsu = { "上诉" },
  qisu = { "起诉" }, beigao = { "被告" }, yuangao = { "原告" }, zhengju = { "证据" },
  zhengren = { "证人" }, diaojie = { "调解" }, zhongcai = { "仲裁" },
  peichang = { "赔偿" }, jiufen = { "纠纷" }, weiquan = { "维权" }, zeren = { "责任" },
  anjian = { "案件" }, jingcha = { "警察" }, baojing = { "报警" },

  chuxing = { "出行" }, lvyou = { "旅游" }, lvxing = { "旅行" }, chufa = { "出发", "处罚" },
  huicheng = { "回程" }, hangban = { "航班" }, huoche = { "火车" }, qiche = { "汽车" },
  zijia = { "自驾" }, luduan = { "路段" }, jiaotong = { "交通" }, anxian = { "安全" },
  qiandao = { "签到" }, qianzheng = { "签证" }, huzhao = { "护照" }, jiudian = { "酒店" },
  banjia = { "搬家" }, qianju = { "迁居" }, huijia = { "回家" }, yuanxing = { "远行" },
  chuguo = { "出国" }, chengshi = { "城市" }, tianqi = { "天气" }, xingcheng = { "行程" },

  jiankang = { "健康" }, shenti = { "身体" }, jibing = { "疾病" }, zhengzhuang = { "症状" },
  yiyuan = { "医院" }, yisheng = { "医生" }, jiancha = { "检查" }, zhiliao = { "治疗" },
  shoushu = { "手术" }, yaowu = { "药物" }, kangfu = { "康复" }, xiuxi = { "休息" },
  shuimian = { "睡眠" }, shimian = { "失眠" }, toutong = { "头痛" }, fashao = { "发烧" },
  ganmao = { "感冒" }, weitong = { "胃痛" }, yali = { "压力" }, xinli = { "心理" },
  qingxu = { "情绪" }, huaiyun = { "怀孕" }, taier = { "胎儿" }, shengyu = { "生育" },

  jiayun = { "家运" }, jiaren = { "家人" }, fuqin = { "父亲" }, muqin = { "母亲" },
  fumu = { "父母" }, haizi = { "孩子" }, erzi = { "儿子" }, nver = { "女儿" },
  zinv = { "子女" }, xiongdi = { "兄弟" }, jiemei = { "姐妹" }, qinqi = { "亲戚" },
  jiatingguanxi = { "家庭关系" }, jiatingmaodun = { "家庭矛盾" }, jiazhai = { "家宅" }, fangzi = { "房子" },
  zhuangxiu = { "装修" }, linju = { "邻居" }, tuanyuan = { "团圆" }, xiaoshun = { "孝顺" },

  yunshi = { "运势" }, mingyun = { "命运" }, yunqi = { "运气" }, jili = { "吉利" },
  jixiong = { "吉凶" }, pingan = { "平安" }, haozhuan = { "好转" }, zhuanji = { "转机" },
  guiren = { "贵人" }, xiaoren = { "小人" }, zhuzhang = { "阻障" }, shunshi = { "顺势" },
  jinqi = { "近期" }, changqi = { "长期" }, duanqi = { "短期" }, jinnian = { "今年" },
  mingnian = { "明年" }, benyue = { "本月" }, xiageyue = { "下个月" },

  kaidian = { "开店" }, gongchang = { "工厂" }, gongzuoshi = { "工作室" }, zhizhao = { "执照" },
  xuanzhi = { "选址" }, zhuangye = { "转业" }, zhuanxing = { "转型" }, hangye = { "行业" },
  shichang = { "市场" }, chanpin = { "产品" }, pinpai = { "品牌" }, tuiguang = { "推广" },
  liuliang = { "流量" }, guke = { "顾客" }, hehuoren = { "合伙人" }, gongyingshang = { "供应商" },

  ren = { "人" }, shiqing = { "事情" }, dongxi = { "东西" }, difang = { "地方" },
  mingzi = { "名字" }, dianhua = { "电话" }, xiaoxi = { "消息" }, xinxi = { "信息" },
  weixin = { "微信" }, pengyou = { "朋友" }, tongzhi = { "通知" }, huifu = { "回复" },
  queren = { "确认" }, tongyi = { "同意" }, jujue = { "拒绝" }, jieshou = { "接受" },
  huode = { "获得" }, shiqu = { "失去" }, daolai = { "到来" }, likai = { "离开" },
  huida = { "回答" }, gaosu = { "告诉" }, xunwen = { "询问" }, biaoshi = { "表示" },
  zhenzheng = { "真正" }, zhongyao = { "重要" }, putong = { "普通" }, teshu = { "特殊" },
  mingxian = { "明显" }, wending = { "稳定" }, heshi = { "合适", "和解" }, zhengque = { "正确" },
  cuowu = { "错误" }, yanzhong = { "严重" }, rongyi = { "容易" }, fuza = { "复杂" },
  qingchu = { "清楚" }, mingbai = { "明白" }, zhunque = { "准确" }, kekao = { "可靠" },

  -- 常用完整问句与判断表达
  woxiangwen = { "我想问" }, woxiangzhidao = { "我想知道" }, qingbangwo = { "请帮我" },
  qingfenxi = { "请分析" }, qinggaosuwo = { "请告诉我" }, zenmeban = { "怎么办" },
  huibuhui = { "会不会" }, nengbuneng = { "能不能" }, yaobuyao = { "要不要" },
  qubuqu = { "去不去" }, gaibugai = { "该不该" }, shifouhege = { "是否合格" },
  shifoushunli = { "是否顺利" }, nengfouchenggong = { "能否成功" }, shenmeshijian = { "什么时间" },
  zuihaoshijian = { "最好时间" }, yibanshunli = { "一般顺利" }, jinzhanruhe = { "进展如何" },
  jieguruhe = { "结果如何" }, houxuruhe = { "后续如何" }, qianjingruhe = { "前景如何" },
  zhidexingdong = { "值得行动" }, shifouheshi = { "是否合适" }, xuyaozhuyi = { "需要注意" },

  -- 学业与考试
  kaoshijieguo = { "考试结果" }, nengfoutongguo = { "能否通过" }, nengfouluqu = { "能否录取" },
  xuexijindu = { "学习进度" }, chengjitisheng = { "成绩提升" }, zhuanyexuanze = { "专业选择" },
  baokaofangxiang = { "报考方向" }, shengxuejieguo = { "升学结果" }, kaoyanjieguo = { "考研结果" },
  gaokaochengji = { "高考成绩" }, lunwenqianjing = { "论文前景" }, biyezhengshu = { "毕业证书" },

  -- 事业、工作与创业
  gongzuoshunli = { "工作顺利" }, mianshijieguo = { "面试结果" }, nengfouruzhi = { "能否入职" },
  nengfoushengzhi = { "能否升职" }, shengzhijiaxin = { "升职加薪" }, gongzuobianhua = { "工作变化" },
  zhiyequshi = { "职业趋势" }, chuangyeshunli = { "创业顺利" }, hezuojieguo = { "合作结果" },
  xiangmujinzhan = { "项目进展" }, zhuanzhengjieguo = { "转正结果" }, tiaocaojihui = { "跳槽机会" },
  shangban = { "上班" }, xiaban = { "下班" }, jiaban = { "加班" }, qingjia = { "请假" },
  zhuanzheng = { "转正" }, shiyongqi = { "试用期" }, laodonghetong = { "劳动合同" },
  shebao = { "社保" }, gongjijin = { "公积金" }, zhichangguanxi = { "职场关系" },

  -- 爱情、婚姻与人际关系
  ganqingfazhan = { "感情发展" }, duifangxintai = { "对方心态" }, nengfoufuhe = { "能否复合" },
  shifoujiehun = { "是否结婚" }, hunyinfazhan = { "婚姻发展" }, lianairuhe = { "恋爱如何" },
  yuanfenruhe = { "缘分如何" }, ganqingwenti = { "感情问题" }, disanfangguanxi = { "第三方关系" },
  liaotian = { "聊天" }, lianluo = { "联络" }, xiangchu = { "相处" }, liangjie = { "谅解" },
  baoqian = { "抱歉" }, chengnuo = { "承诺" }, shifoulianxi = { "是否联系" },
  duifangtaidu = { "对方态度" }, ganqingzhuanji = { "感情转机" }, hunyinjieguo = { "婚姻结果" },

  -- 财运、交易与经营
  caiyunruhe = { "财运如何" }, touzishunli = { "投资顺利" }, nengfouyingli = { "能否盈利" },
  shengyiruhe = { "生意如何" }, maimaifazhan = { "买卖发展" }, zijinzhouzhuan = { "资金周转" },
  zhaiwujiejue = { "债务解决" }, huikuanjindu = { "回款进度" }, shichangqianjing = { "市场前景" },
  chanpinxiaoliang = { "产品销量" }, hehuorenguanxi = { "合伙人关系" }, kaidianshunli = { "开店顺利" },
  xuanzhifangxiang = { "选址方向" }, shengyifazhan = { "生意发展" }, fangzu = { "房租" },
  zufang = { "租房" }, maiche = { "买车" }, cheliang = { "车辆" }, baoxian = { "保险" },

  -- 丢失、寻物与方位
  dongxizainali = { "东西在哪里" }, nengfouzhaodao = { "能否找到" }, shiwufangwei = { "失物方位" },
  shifoubeitou = { "是否被偷" }, xunzhaofangxiang = { "寻找方向" }, diushididian = { "丢失地点" },
  zuihouweizhi = { "最后位置" }, kenengfangwei = { "可能方位" }, shiwuxiansuo = { "失物线索" },
  nengfouzhuihui = { "能否追回" }, shifouyilou = { "是否遗漏" }, xunzhaojieguo = { "寻找结果" },

  -- 诉讼、合同与纠纷
  susongjieguo = { "诉讼结果" }, guansishengfu = { "官司胜负" }, panjuejieguo = { "判决结果" },
  tiaojieshunli = { "调解顺利" }, zhengjushouji = { "证据收集" }, anjianjinzhan = { "案件进展" },
  hetongjiufen = { "合同纠纷" }, peichangjieguo = { "赔偿结果" }, shifoushangsu = { "是否上诉" },
  lvshijianyi = { "律师建议" }, kaitingjieguo = { "开庭结果" }, weiquanfangshi = { "维权方式" },

  -- 出行、迁移与天气交通
  chuxingshunli = { "出行顺利" }, shifoukequ = { "是否可去" }, nengfouchufa = { "能否出发" },
  xingchenganpai = { "行程安排" }, jiaotonganquan = { "交通安全" }, tianqiqingkuang = { "天气情况" },
  hangbanzhuangtai = { "航班状态" }, chuxingshijian = { "出行时间" }, banjiashunli = { "搬家顺利" },
  qianjufangxiang = { "迁居方向" }, yuanxingpingan = { "远行平安" }, huichengshijian = { "回程时间" },

  -- 健康、家庭与运势
  shentizhuangkuang = { "身体状况" }, bingqingfazhan = { "病情发展" }, shoushushunli = { "手术顺利" },
  kangfujindu = { "康复进度" }, jiankangjianyi = { "健康建议" }, shifouhuaiyun = { "是否怀孕" },
  jiatinghexie = { "家庭和谐" }, jiatingfazhan = { "家庭发展" }, jiazhaiyunshi = { "家宅运势" },
  zinvjiaoyu = { "子女教育" }, fumuguanxi = { "父母关系" }, jinqiyunshi = { "近期运势" },
  jinnianyunshi = { "今年运势" }, mingnianyunshi = { "明年运势" }, yunshifazhan = { "运势发展" },
  shifoujili = { "是否吉利" }, guirenzhuli = { "贵人助力" }, shenghuo = { "生活" },
  kuaidi = { "快递" }, wuliu = { "物流" }, dingwei = { "定位" }, dizhi = { "地址" },
  mima = { "密码" }, zhanghao = { "账号" }, yinsi = { "隐私" }, wangluo = { "网络" },
}
